---
abstract: A simple Windows message loop with a timeout
author:
  - 'Michael Roberts <michael@vivtek.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-MessageLoop
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
version: 0.03
